### PR TITLE
Update plotting.py

### PR DESCRIPTION
**Pull request by jeffschwane**
I think there was an issue in the code when the parameter ylim is set. axes[0] yields an object not subscribable error.

### CODE REVIEW

**Comment by rdesmond** [comment]
Thanks Jeff! We'll take a look!

**Review by giladgressel — APPROVED** [review]
Right!! I had modified this from the original here
https://scikit-learn.org/stable/auto_examples/model_selection/plot_learning_curve.html

Which had used 3 subplots, so you needed to subscript axes. However I changed that behavior everywhere except the `ylim`.

Great catch and thank you for the PR fix.

**Comment by jeffschwane** [comment]
No prob! Did I initiate the pull request correctly? It was my first time...

**Comment by giladgressel** [comment]
Yes, you did it perfectly! Congrats on your first PR and first MERGE! May you see many more 😁

**Comment by jeffschwane** [comment]
Thanks!

**Comment by rdesmond** [comment]
Ya, perfect! Nice work, team!

**Pull request merged**
